{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-drought4r
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/drought4R/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d0646ed8e6d8b983e6621fb27d6cfbe7accb1398bd5a8ef34eddd7415e05c82b

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-spei >=1.8.1
    - r-abind
    - r-magrittr
    - r-geosphere
    - r-transformer >=1.4.4
  run:
    - r-base
    - r-spei >=1.8.1
    - r-abind
    - r-magrittr
    - r-geosphere
    - r-transformer >=1.4.4

test:
  commands:
    - $R -e "library('drought4R')"           # [not win]
    - "\"%R%\" -e \"library('drought4R')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Evapotranspiration routines and drought index calculation using the climate4R framework <https://github.com/SantanderMetGroup/climate4R>.
  doc_url: https://github.com/SantanderMetGroup/drought4R
  dev_url: https://github.com/SantanderMetGroup/drought4R
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa


# Package: drought4R
# Depends: R(>= 3.5.0)
# Imports: SPEI(>=1.8.1), transformeR(>= 1.4.4), utils, abind, magrittr
# Suggests: loadeR, visualizeR, convertR
# Type: Package
# Title: A climate4R package for drought assessment <http://www.meteo.unican.es/climate4R>
# Version: 0.2.0
# Date: 2019-04-24
# Authors@R: as.person(c( "Santander Meteorology Group <http://meteo.unican.es> [cph]", "Joaquin Bedia <bediaj@unican.es> [aut, cre]", "Maialen Iturbide <miturbide@ifca.unican.es> [aut]"))
# BugReports: https://github.com/SantanderMetGroup/drought4R/issues
# URL: https://github.com/SantanderMetGroup/transformeR/wiki
# Description: Evapotranspiration routines and drought index calculation using the climate4R framework <http://www.meteo.unican.es/climate4R>.
# License: file LICENSE
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 6.1.1
